donor/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView
from . import views
urlpatterns = [
    path('donorlogin', LoginView.as_view(template_name='donor/donorlogin.html'),name='donorlogin'),
    path('donorsignup', views.donor_signup_view,name='donorsignup'),
    path('donor-dashboard', views.donor_dashboard_view,name='donor-dashboard'),
    path('donate-blood', views.donate_blood_view,name='donate-blood'),
    path('donation-history', views.donation_history_view,name='donation-history'),
    path('make-request', views.make_request_view,name='make-request'),
    path('request-history', views.request_history_view,name='request-history'),
]

hospitalmanagement/urls.py
from django.contrib import admin
from django.urls import path,include
from hospital import views

from django.contrib.auth.views import LoginView,LogoutView


#-------------FOR ADMIN RELATED URLS
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home_view,name=''),


    path('aboutus', views.aboutus_view),
    path('contactus', views.contactus_view),


    path('adminclick', views.adminclick_view),
    path('doctorclick', views.doctorclick_view),
    path('patientclick', views.patientclick_view),

    path('adminsignup', views.admin_signup_view),
    path('doctorsignup', views.doctor_signup_view,name='doctorsignup'),
    path('patientsignup', views.patient_signup_view),
    
    path('adminlogin', LoginView.as_view(template_name='hospital/adminlogin.html')),
    path('doctorlogin', LoginView.as_view(template_name='hospital/doctorlogin.html')),
    path('patientlogin', LoginView.as_view(template_name='hospital/patientlogin.html')),


    path('afterlogin', views.afterlogin_view,name='afterlogin'),
    path('logout', LogoutView.as_view(template_name='hospital/index.html'),name='logout'),


    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),

    path('admin-view-doctor', views.admin_view_doctor_view,name='admin-view-doctor'),
    path('admin_doctor_history', views.admin_doctor_history,name='admin_doctor_history'),
    path('delete-doctor-from-hospital/<int:pk>', views.delete_doctor_from_hospital_view,name='delete-doctor-from-hospital'),
    path('update-doctor/<int:pk>', views.update_doctor_view,name='update-doctor'),
    path('admin-add-doctor', views.admin_add_doctor_view,name='admin-add-doctor'),
    path('admin-approve-doctor', views.admin_approve_doctor_view,name='admin-approve-doctor'),
    path('approve-doctor/<int:pk>', views.approve_doctor_view,name='approve-doctor'),
    path('reject-doctor/<int:pk>', views.reject_doctor_view,name='reject-doctor'),
    path('admin-view-doctor-specialisation',views.admin_view_doctor_specialisation_view,name='admin-view-doctor-specialisation'),


    path('admin-view-patient', views.admin_view_patient_view,name='admin-view-patient'),
    path('delete-patient-from-hospital/<int:pk>', views.delete_patient_from_hospital_view,name='delete-patient-from-hospital'),
    path('update-patient/<int:pk>', views.update_patient_view,name='update-patient'),
    path('admin-add-patient', views.admin_add_patient_view,name='admin-add-patient'),
    path('admin-approve-patient', views.admin_approve_patient_view,name='admin-approve-patient'),
    path('approve-patient/<int:pk>', views.approve_patient_view,name='approve-patient'),
    path('reject-patient/<int:pk>', views.reject_patient_view,name='reject-patient'),
    path('admin-discharge-patient', views.admin_discharge_patient_view,name='admin-discharge-patient'),
    path('discharge-patient/<int:pk>', views.discharge_patient_view,name='discharge-patient'),
    path('download-pdf/<int:pk>', views.download_pdf_view,name='download-pdf'),


    path('admin-view-appointment', views.admin_view_appointment_view,name='admin-view-appointment'),
    path('admin-add-appointment', views.admin_add_appointment_view,name='admin-add-appointment'),
    path('admin-approve-appointment', views.admin_approve_appointment_view,name='admin-approve-appointment'),
    path('approve-appointment/<int:pk>', views.approve_appointment_view,name='approve-appointment'),
    path('reject-appointment/<int:pk>', views.reject_appointment_view,name='reject-appointment'),
]


#---------FOR DOCTOR RELATED URLS-------------------------------------
urlpatterns +=[
    path('doctor-dashboard', views.doctor_dashboard_view,name='doctor-dashboard'),
    path('search', views.search_view,name='search'),

    path('doctor-patient', views.doctor_patient_view,name='doctor-patient'),
    path('doctor-view-patient', views.doctor_view_patient_view,name='doctor-view-patient'),
    path('doctor-view-discharge-patient',views.doctor_view_discharge_patient_view,name='doctor-view-discharge-patient'),

    path('doctor-appointment', views.doctor_appointment_view,name='doctor-appointment'),
    path('doctor-view-appointment', views.doctor_view_appointment_view,name='doctor-view-appointment'),
    path('doctor-delete-appointment',views.doctor_delete_appointment_view,name='doctor-delete-appointment'),
    path('delete-appointment/<int:pk>', views.delete_appointment_view,name='delete-appointment'),

]




#---------FOR PATIENT RELATED URLS-------------------------------------
urlpatterns +=[

    path('patient-dashboard', views.patient_dashboard_view,name='patient-dashboard'),
    path('patient-appointment', views.patient_appointment_view,name='patient-appointment'),
    path('patient-book-appointment', views.patient_book_appointment_view,name='patient-book-appointment'),
    path('patient-view-appointment', views.patient_view_appointment_view,name='patient-view-appointment'),
    path('patient-view-doctor', views.patient_view_doctor_view,name='patient-view-doctor'),
    path('searchdoctor', views.search_doctor_view,name='searchdoctor'),
    path('patient-discharge', views.patient_discharge_view,name='patient-discharge'),

]


#---------FOR Donor RELATED URLS-------------------------------------
urlpatterns +=[
path('donor/',include('donor.urls')),

path('admin-donor', views.admin_donor_view,name='admin-donor'),
path('update-donor/<int:pk>', views.update_donor_view,name='update-donor'),
path('delete-donor/<int:pk>', views.delete_donor_view,name='delete-donor'),

path('admin-request', views.admin_request_view,name='admin-request'),



path('admin_donation_history', views.admin_donation_history,name='admin_donation_history'),
path('admin-donation', views.admin_donation_view,name='admin-donation'),
path('approve-donation/<int:pk>', views.approve_donation_view,name='approve-donation'),
path('reject-donation/<int:pk>', views.reject_donation_view,name='reject-donation'),



path('admin-request-history', views.admin_request_history_view,name='admin-request-history'),
path('update-approve-status/<int:pk>', views.update_approve_status_view,name='update-approve-status'),
path('update-reject-status/<int:pk>', views.update_reject_status_view,name='update-reject-status'),

path('admin-blood', views.admin_blood_view,name='admin-blood'),


]

#---------FOR Admin RELATED URLS-------------------------------------
urlpatterns +=[
    path('admin_edit_doctor/<int:pk>/', views.update_doctor_view, name="admin_edit_doctor"),
    path('patient_personalRecords/<pk>/',views.patient_personalRecords,name='patient_record'),
    path('add_pharmacist/',views.createPharmacist,name='add_pharmacist'),

    path('manage_pharmacist/',views.managePharmacist,name='manage_pharmacist'),
    path('edit_pharmacist/<int:pk>/', views.editPharmacist, name="edit_pharmacist"),
    path('delete_pharmacist/<str:pk>/',views.deletePharmacist,name='delete_pharmacist'),

    path('add_stock/',views.addStock,name='add_stock'),
    path('add_category/',views.addCategory,name='add_category'),
    path('manage_stock/',views.manageStock,name='manage_stock'),    
    path('prescribe_drug/',views.addPrescription,name='prescribe'),
    path('reorder_level/<str:pk>/', views.reorder_level, name="reorder_level"),
    path('edit_drug/<pk>/', views.editStock, name="edit_drug"),
    path('delete_drug/<str:pk>/',views.deleteDrug,name='delete_drug'),
    path('drug_details/<str:pk>/', views.drugDetails, name="drug_detail"),
    path('receive_drug/<pk>/', views.receiveDrug, name="receive_drug"),

    path('doctor_prescribe_drug/<str:pk>/',views.addPrescription2,name='doctor_prescribe_drug'),
    path('patient_personalDetails/<str:pk>/',views.patient_personalDetails,name='patient_record_doctor'),
    path('patient_feedback/',views.patient_feedback,name='patient_feedback'),
    path('staff_feedback_save/', views.patient_feedback_save, name="patient_feedback_save"),

path('patient_feedback_message/', views.patient_feedback_message, name="patient_feedback_message"),
path('patient_feedback_message_reply/', views.patient_feedback_message_reply, name="patient_feedback_message_reply"),

]

hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models import BooleanField, ExpressionWrapper, Q
from django.db.models.functions import Now

departments=[('Cardiologist','Cardiologist'),
('Dermatologists','Dermatologists'),
('Emergency Medicine Specialists','Emergency Medicine Specialists'),
('Allergists/Immunologists','Allergists/Immunologists'),
('Anesthesiologists','Anesthesiologists'),
('Colon and Rectal Surgeons','Colon and Rectal Surgeons')
]
class Doctor(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/DoctorProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=True)
    department= models.CharField(max_length=50,choices=departments,default='Cardiologist')
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return "{} ({})".format(self.user.first_name,self.department)



class Patient(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='static/profile_pic/PatientProfilePic/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    symptoms = models.CharField(max_length=100,null=False)
    assignedDoctorId = models.PositiveIntegerField(null=True)
    admitDate=models.DateField(auto_now=True)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_id(self):
        return self.user.id
    def __str__(self):
        return self.user.first_name+" ("+self.symptoms+")"



class Pharmacist(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='static/profile_pic/Pharmacist/',null=True,blank=True,default = None)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
    status=models.BooleanField(default=False)
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    
    



class Appointment(models.Model):
    patientId=models.PositiveIntegerField(null=True)
    doctorId=models.PositiveIntegerField(null=True)
    patientName=models.CharField(max_length=40,null=True)
    doctorName=models.CharField(max_length=40,null=True)
    appointmentDate=models.DateField(auto_now=True)
    description=models.TextField(max_length=500)
    status=models.BooleanField(default=False)



class PatientDischargeDetails(models.Model):
    patientId=models.PositiveIntegerField(null=True)
    patientName=models.CharField(max_length=40)
    assignedDoctorName=models.CharField(max_length=40)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=True)
    symptoms = models.CharField(max_length=100,null=True)
    admitDate=models.DateField(null=False)
    releaseDate=models.DateField(null=False)
    daySpent=models.PositiveIntegerField(null=False)
    roomCharge=models.PositiveIntegerField(null=False)
    medicineCost=models.PositiveIntegerField(null=False)
    doctorFee=models.PositiveIntegerField(null=False)
    OtherCharge=models.PositiveIntegerField(null=False)
    total=models.PositiveIntegerField(null=False)



class Category(models.Model):
    name = models.CharField(max_length=50, blank=False, null=True)
    
    def __str__(self):
        return str(self.name)

    
class Prescription(models.Model):
    patient_id = models.ForeignKey(Patient,null=True, on_delete=models.SET_NULL)
    description=models.TextField(null=True)
    prescribe=models.CharField(max_length=100,null=True)
    date_precribed=models.DateTimeField(auto_now_add=True, auto_now=False)



class ExpiredManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().annotate(
            expired=ExpressionWrapper(Q(valid_to__lt=Now()), output_field=BooleanField())
        )

class Stock(models.Model):
    category = models.ForeignKey(Category,null=True,on_delete=models.CASCADE,blank=True)
    drug_imprint=models.CharField(max_length=6 ,blank=True, null=True)
    drug_name = models.CharField(max_length=50, blank=True, null=True)
    drug_color = models.CharField(max_length=50, blank=True, null=True)
    drug_shape = models.CharField(max_length=50, blank=True, null=True)
    quantity = models.IntegerField(default='0', blank=True, null=True)
    receive_quantity = models.IntegerField(default='0', blank=True, null=True)
    reorder_level = models.IntegerField(default='0', blank=True, null=True)
    manufacture= models.CharField(max_length=50, blank=True, null=True)
    last_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    drug_strength= models.CharField(max_length=10, blank=True, null=True)
    valid_from = models.DateTimeField(blank=True, null=True,default=timezone.now)
    valid_to = models.DateTimeField(blank=False, null=True)
    drug_description=models.TextField(blank=True,max_length=1000,null=True)
    drug_pic=models.ImageField(default="images2.png",null=True,blank=True)
    objects = ExpiredManager()
   
    def __str__(self):
        return str(self.drug_name)

 
class Dispense(models.Model):
    patient_id = models.ForeignKey(Patient, on_delete=models.DO_NOTHING,null=True)
    drug_id = models.ForeignKey(Stock, on_delete=models.SET_NULL,null=True,blank=False)
    dispense_quantity = models.PositiveIntegerField(default='1', blank=False, null=True)
    taken=models.CharField(max_length=300,null=True, blank=True)
    stock_ref_no=models.CharField(max_length=300,null=True, blank=True)
    instructions=models.TextField(max_length=300,null=True, blank=False)
    dispense_at = models.DateTimeField(auto_now_add=True,null=True, blank=True)


class PatientFeedback(models.Model):
    id = models.AutoField(primary_key=True)
    patient_id = models.ForeignKey(Patient, on_delete=models.CASCADE)
    
    pharmacist_id=models.ForeignKey( Pharmacist,null=True, on_delete=models.CASCADE)
    feedback = models.TextField(null=True)
    feedback_reply = models.TextField(null=True)
    admin_created_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = models.Manager()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
 
  
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css'  %}">

 
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link href="{% static 'jquery-ui2/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.theme.min.css' %}" rel="stylesheet">



</head>
<body>
{% block main_content %}
{% endblock %}
   

<script>
  setTimeout(function() {
$('.alert').fadeOut();
}, 1200); 
</script>
  




</script>
<script src="{% static "jquery/jquery.min.js"  %}"></script>

<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>

<script src="{% static 'jquery-ui2/jquery-ui.min.js' %}"></script>
<script src="{% static 'jquery-ui2/jquery-ui.js' %}"></script>
<script src="{% static 'js/datejs.js' %}"></script>


</body>
</html>

templates/base_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pharmacy Dispensing System</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
    <link rel="stylesheet" href="{% static 'css/profile.css'%}">

    <link rel="stylesheet" href="{% static "fontawesome-free/css/all.min.css" %}">
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
 
  
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.css'  %}">
  <link rel="stylesheet" href="{% static 'pace-progress/themes/black/pace-theme-flat-top.css' %}">
  <link rel="stylesheet" href="{% static 'datatables-bs4/css/dataTables.bootstrap4.min.css'%}">
  <link rel="stylesheet" href="{% static 'datatables-responsive/css/responsive.bootstrap4.min.css'%}">
  <link rel="stylesheet" href="{% static 'datatables-buttons/css/buttons.bootstrap4.min.css'%}">
  <link rel="stylesheet" href="{% static 'css/select2.css' %}">
 
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link href="{% static 'jquery-ui2/jquery-ui.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.structure.min.css' %}" rel="stylesheet">
  <link href="{% static 'jquery-ui2/jquery-ui.theme.min.css' %}" rel="stylesheet">


</head>
{% block htm %}


{% endblock htm%}



<script src="{% static "jquery/jquery.min.js"  %}"></script>

<!-- Bootstrap 4 -->
<script src="{% static "bootstrap/js/bootstrap.bundle.min.js"  %}"></script>

<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js'  %}"></script>

<script src="{% static 'jquery-ui2/jquery-ui.min.js' %}"></script>
<script src="{% static 'jquery-ui2/jquery-ui.js' %}"></script>
<!-- jquery slimscroll js -->
<script src="{% static 'jquery-slimscroll/js/jquery.slimscroll.js'%}"></script>
<!-- modernizr js -->
<!-- classie js -->
<!-- i18next.min.js -->
<script  src="{% static 'i18next/js/i18next.min.js'%}"></script>
<script src="{% static 'i18next-xhr-backend/js/i18nextXHRBackend.min.js'%}"></script>

<script src="{% static 'js/paging.js' %}"></script>


<script src="{% static 'pace-progress/pace.min.js' %}"></script>

<script src="{% static 'datatables/jquery.dataTables.js'%}"></script>
<script src="{% static 'datatables-bs4/js/dataTables.bootstrap4.min.js'%} "></script>
<script src="{% static 'datatables-responsive/js/dataTables.responsive.min.js'%} "></script>
<script src="{% static 'datatables-responsive/js/responsive.bootstrap4.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/dataTables.buttons.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.bootstrap4.min.js'%}"></script>
<script src="{% static 'pdfmake/pdfmake.min.js'%}"></script>
<script src="{% static 'pdfmake/vfs_fonts.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.html5.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.print.min.js'%}"></script>
<script src="{% static 'datatables-buttons/js/buttons.colVis.min.js'%}"></script>
<script src="{% static 'js/select2.min.js'%}"></script>

<script src="{% static 'js/datejs.js' %}"></script>

 {% block  js%}
 {% endblock %}
 <script>
   $(document).ready(function(){
  $(function () {

    $("#plist").DataTable({
      "responsive": true, "lengthChange": true, "autoWidth": false,
      "buttons": ["excel","print"],
      "lengthMenu": [5]
    }).buttons().container().appendTo('#plist_wrapper .col-md-6:eq(0)');
    // $('#plist').DataTable({
    //   "lengthChange": true,
     
    //   "lengthMenu":[5]
    // });
  
  });
});
 </script>

 <script>

$("#id_drug_id").select2({
    placeholder: "Dispense Drug Here",
    allowClear: true
});
$("#id_drug_id").select2();
$("#id_drug_id").on("select2:open", function (e) {
  
  $('#id_drug_id').change(function(){
        var data= $(this).val();
        // alert(data);       
        $("#id_taken").val(data)
         
      });

     $('#select2-search__field')
         .text(drugname)
         .trigger('change');
});
$('#id_drug_id').select2({
    placeholder:" Search Dispense Drug here",
    width:"100%",
    height:"45px"



 });


</script>
</body>
</html>